add page objects for waiting room
dvsa/dvsa-des-automation pull request #10
Opened 2021-08-03 10:58 UTC by ditmirDVSA

2021-08-03 11:15 UTC, turnerc1 requested changes

2021-08-03 11:15 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        }
Have you added the validation text for the signature pad and the two check boxes to this list.

2021-08-04 08:06 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        }
done

2021-08-04 09:00 UTC, turnerc1 approved these changes

2021-08-04 10:24 UTC, merged