Mes 8333 adi3 unsuccessful
dvsa/dvsa-des-automation pull request #109
Opened 2022-10-31 07:05 UTC by turnerc1

## Description

Unsuccessful test with insufficient score 
Unsuccessful test with insufficient risk management
## Checklist

- [ ] PR title includes the JIRA ticket number and an understandable description
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket

2022-10-31 08:27 UTC, JCarterDVSA reviewed
delete commented code

2022-10-31 08:27 UTC, JCarterDVSA commented on src/pageobjects/des/login.pageobject.ts
> +    console.log('>>>>>>>>>SIGNED OUT>>>>>>>>>');
delete commented code

2022-10-31 08:29 UTC, JCarterDVSA approved these changes

2022-10-31 09:38 UTC, Cullima requested changes

2022-10-31 09:38 UTC, Cullima commented on src/pageobjects/des/testReport.pageobject.ts
> +  async keyboardClickLetter(): Promise<void> {
doesn't feel like this method belongs in a page object if it is a generic function for pressing an ios keyboard key.  Can you add a description for the method so people know how to use it and what it does.  Also, worth looking at simpler methods for interacting with the keyboard, e.g. https://webdriver.io/docs/api/appium/#hidekeyboard

2022-11-02 13:59 UTC, turnerc1 commented on src/pageobjects/des/testReport.pageobject.ts
> +  async keyboardClickLetter(): Promise<void> {
I have switched out the original function contents to driver.hideKeyboard().

2022-11-02 14:13 UTC, JCarterDVSA approved these changes

2022-11-02 16:13 UTC, Cullima commented on src/pageobjects/des/login.pageobject.ts
> +  async clickNativeButtonWithText(text: string): Promise<void> {
this seems generic enough to move to a base page object ?

2022-11-02 16:15 UTC, Cullima commented on src/pageobjects/des/testReport.pageobject.ts
> +  async keyboardClickLetter(letter:string): Promise<void> {
can we also add this to the base page object seems fairly gneric

2022-11-03 10:45 UTC, Cullima approved these changes

2022-11-03 10:45 UTC, Cullima commented on src/pageobjects/des/login.pageobject.ts
> +// export interface Context {
can you delete if not needed

2022-11-03 10:47 UTC, JCarterDVSA approved these changes

2022-11-03 10:58 UTC, merged