add objects and selectors for comms screen page
dvsa/dvsa-des-automation pull request #11
Opened 2021-08-05 10:28 UTC by ditmirDVSA

MES-7022

2021-08-09 09:56 UTC, turnerc1 requested changes

2021-08-09 09:56 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +    ],
There is also a "by email (provided at booking time)" field which is not mentioned here. Are you able to do this field as well please?

2021-08-09 09:56 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +    ],
AS well as the back button, screen title, end test button? Are you able to do these as well.

2021-08-09 10:00 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +    ],
The by email is already specified here             "select-email-radio-btn":"input[id='newEmail']",
 
The other buttons for end test and back are specified too in the globalelements, I will however move these buttons into des-general as they apply to many pages

2021-08-09 10:10 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +    ],
You have the "New Email" but not the existing email. CHeck the miro board for this page.

2021-08-09 10:28 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +    ],
That option is not built 

<img width="534" alt="Screenshot 2021-08-09 at 11 27 32" src="https://user-images.githubusercontent.com/87806009/128693062-b9ccd1bc-940c-4003-a434-36a0fb267b07.png">

2021-08-09 11:10 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +    ],
That option is build check other tests

2021-08-09 11:29 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +    ],
which tests ? This is the app I've loaded , doesn't appear it is on there

2021-08-10 08:25 UTC, turnerc1 approved these changes

2021-08-10 10:03 UTC, merged