add elements for waiting room to car
dvsa/dvsa-des-automation pull request #12
Opened 2021-08-10 09:49 UTC by ditmirDVSA

mes-7023

2021-08-10 12:41 UTC, turnerc1 requested changes

2021-08-10 12:41 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        "modal-submit-btn":"//button[contains(text(), 'Submit')]",
I have tried to see if this one is in the elements tab when the simulator is open but it does not appear.

2021-08-10 12:41 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        "modal-cancel-btn":"//button[contains(text(), 'Cancel')]",
I have tried to see if this one is in the elements tab when the simulator is open but it does not appear.

2021-08-10 12:41 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        "tell-me-validation-error-msg":"#waiting-room-to-car-tell-me-validation-text",
THere is a second validation error when the user selects a tell me questions but does not answer it. Please add it

2021-08-10 12:41 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        "manual-transmission-btn":"#transmission-manual-a6f6e3c1-72b6-4d60-9315-b539031fe6c3",
The manual button when searched for does not exist

2021-08-10 12:41 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        "automatic-transmission-btn":"#transmission-automatic-a6f6e3c1-72b6-4d60-9315-b539031fe6c3",
The automatic button when searched for does not exist

2021-08-10 12:41 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        "view-test-centre-journal-btn":"//ion-button[contains(text(), 'View test centre journal')]",
I have tried to see if this one is in the elements tab when the simulator is open but it does not appear.

2021-08-10 12:41 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        "continue-to-test-report-btn":"//ion-button[contains(text(), 'Continue to test report')]"
I have tried to see if this one is in the elements tab when the simulator is open but it does not appear.

2021-08-11 10:52 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        "modal-submit-btn":"//button[contains(text(), 'Submit')]",
Thats using path to find a button by name as it didn't have an ID

2021-08-11 10:53 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        "automatic-transmission-btn":"#transmission-automatic-a6f6e3c1-72b6-4d60-9315-b539031fe6c3",
The ID will need to be changed then to remove the extra characters after #transmission-automatic

2021-08-11 10:53 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        "view-test-centre-journal-btn":"//ion-button[contains(text(), 'View test centre journal')]",
these are xpaths

2021-08-11 10:54 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        "continue-to-test-report-btn":"//ion-button[contains(text(), 'Continue to test report')]"
again ... these are xpaths  no ID for them exists

2021-08-11 10:54 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        "modal-cancel-btn":"//button[contains(text(), 'Cancel')]",
path .. no ID exists for them

2021-08-11 10:56 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        "tell-me-questions-options":".select-interface-option",
you'll have to create a custom function to select radio options. We don't want to hard code these options here as they can change

2021-08-11 10:57 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        "manual-transmission-btn":"#transmission-manual-a6f6e3c1-72b6-4d60-9315-b539031fe6c3",
if that ID is subject to change and extra stuff has been added to make it dynamic , we should ask the developers to remove the dynamic part

2021-08-12 06:54 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        "tell-me-questions-options":".select-interface-option",
handled by search team which is re-usable here

2021-08-12 08:20 UTC, turnerc1 requested changes

2021-08-12 08:20 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        "tell-me-questions-options":".select-interface-option",
Will you input search-teams function to fix this? If not please do.

2021-08-12 10:57 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        "tell-me-validation-error-msg":"#waiting-room-to-car-tell-me-validation-text",
No there is a second validation message that appears

2021-08-13 10:10 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        "tell-me-questions-options":".select-interface-option",
this is not the scope of this ticket as far as I'm aware .. we'll implement it once we need it

2021-08-13 10:13 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +        "tell-me-validation-error-msg":"#waiting-room-to-car-tell-me-validation-text",
that is the only one that shows up. looks correct to me 

<img width="1359" alt="Screenshot 2021-08-12 at 10 48 01" src="https://user-images.githubusercontent.com/87806009/129342171-1538465a-e346-4472-add4-50dfc3af0afe.png">

2021-08-13 11:05 UTC, turnerc1 approved these changes

2021-08-13 11:12 UTC, merged