add debrief page objects
dvsa/dvsa-des-automation pull request #14
Opened 2021-08-20 10:23 UTC by ditmirDVSA

MES-7024

2021-08-20 10:31 UTC, turnerc1 requested changes

2021-08-20 10:31 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +        }
you are missing serious faults heading, what the serious fault is, dangerous faults heading, what the dangerous fault is. 
As well as the test outcome result (even though it doesnt have an ID right now, it would still be good to have a path that we can change.)

2021-08-23 12:15 UTC, turnerc1 requested changes

2021-08-23 12:15 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +            "test-outcome-fail":".test-outcome-container failed",
There is a terminate out come aswell

2021-08-24 08:53 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +            "test-outcome-fail":".test-outcome-container failed",
To be honest you really just need 1 selector fo the container ".test-outcome-container" because in the real tests you would check the contents of that container and assert wether the test passed , failed or was terminated by expecting the text to be either of those

2021-08-24 08:59 UTC, turnerc1 approved these changes

2021-08-24 11:02 UTC, merged