update elements for declaration page
dvsa/dvsa-des-automation pull request #17
Opened 2021-09-02 08:34 UTC by ditmirDVSA

2021-09-02 10:55 UTC, turnerc1 requested changes

2021-09-02 10:55 UTC, turnerc1 commented on src/support/globalelements/globalelements.json
> +            "continue-modal-continue-btn":"button='Continue'"
missing one other validation error message

2021-09-03 10:53 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +            "continue-modal-continue-btn":"button='Continue'"
which one is that

2021-09-03 10:58 UTC, ditmirDVSA commented on src/support/globalelements/globalelements.json
> +            "continue-modal-continue-btn":"button='Continue'"
This has been added as warning_text

2021-09-03 11:05 UTC, turnerc1 approved these changes

2021-09-06 07:40 UTC, merged