MES-7752
dvsa/dvsa-des-automation pull request #43
Opened 2022-03-11 07:44 UTC by dhDVSA

REFACTOR waitForSpinningWheel custom 
MES-7752

2022-03-11 08:05 UTC, matthew2564 commented on src/support/common/action/waitForSpinningWheel.ts
> +    const contexts: Array<any> = await driver.getContexts();
This and line ```14``` appear to be unused, if that is the case then i suggest removing them.

2022-03-11 08:35 UTC, Cullima requested changes
Should be moved to shared repo, refactored and then this repo repointed to pull from shared

2022-03-11 15:49 UTC, matthew2564 approved these changes

2022-03-11 15:55 UTC, Cullima requested changes
Need to `npm i @dvsa/app-dev-automation@0.0.11`

2022-03-16 10:52 UTC, Cullima approved these changes

2022-03-16 14:50 UTC, merged