Testjournal Script Refactor
dvsa/dvsa-des-automation pull request #61
Opened 2022-03-24 09:04 UTC by gabrielngdvsa

## Description

Test Journal Refactor 

## Checklist

- [ ] PR title includes the JIRA ticket number and an understandable description
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket

2022-03-24 10:15 UTC, turnerc1 requested changes

2022-03-24 10:15 UTC, turnerc1 commented on src/element-references/des-element-references.json
> +  "test-center-journal": {
Something minor, but are you able to add "des-" at the start of this please. We will try and follow like the dashboard please.

2022-03-24 10:18 UTC, Cullima approved these changes

2022-03-25 10:15 UTC, turnerc1 requested changes

2022-03-25 10:15 UTC, turnerc1 commented on src/features/des/testcentreJournal.feature
> +        Then I wait on element "test-center-journal::journal-button" to be displayed
Update to new page title (des-test-center-journal)

2022-03-25 10:15 UTC, turnerc1 commented on src/features/des/testcentreJournal.feature
> +        When I click on the element "test-center-journal::journal-button"
Update to new page title (des-test-center-journal)

2022-03-25 10:15 UTC, turnerc1 commented on src/features/des/testcentreJournal.feature
> +        Then I wait on element "test-center-journal::page-title" to be displayed
Update to new page title (des-test-center-journal)

2022-03-25 10:15 UTC, turnerc1 commented on src/features/des/testcentreJournal.feature
> +        Then I expect that element "test-center-journal::page-title" matches the text "Candidate search"
Update to new page title (des-test-center-journal)

2022-03-25 10:15 UTC, turnerc1 commented on src/features/des/testcentreJournal.feature
> +        And I expect that element "test-center-journal::location-text" matches the text "Example Test Centre"
Update to new page title (des-test-center-journal)

2022-03-25 10:15 UTC, turnerc1 commented on src/features/des/testcentreJournal.feature
> +        And I add "Ali Campbell" to the inputfield "test-center-journal::candidiate-search-text"
Update to new page title (des-test-center-journal)

2022-03-25 10:15 UTC, turnerc1 commented on src/features/des/testcentreJournal.feature
> +        And I wait on element "test-center-journal::show-booking-button" to be enabled
Update to new page title (des-test-center-journal)

2022-03-25 10:15 UTC, turnerc1 commented on src/features/des/testcentreJournal.feature
> +        And I click on the element "test-center-journal::show-booking-button"
Update to new page title (des-test-center-journal)

2022-03-25 10:15 UTC, turnerc1 commented on src/features/des/testcentreJournal.feature
> +        And I expect that element "test-center-journal::candidiate-booking-message" matches the text "This candidate does not have a booking at Example Test Centre for tomorrow."
Update to new page title (des-test-center-journal)

2022-03-25 11:15 UTC, turnerc1 approved these changes

2022-03-25 11:17 UTC, merged