Mes 7482
dvsa/dvsa-des-automation pull request #63
Opened 2022-03-29 17:07 UTC by turnerc1

## Description

* PLEASE INSERT DESCRIPTION

## Checklist

- [ ] PR title includes the JIRA ticket number and an understandable description
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket

2022-03-29 20:16 UTC, dhDVSA commented on src/pageobjects/des/finalOutcomeScreen.pageobject.ts
> +      if (d255.toLowerCase() === 'no') {
just a slight suggestion :

could do a switch statement here 
switch(d255.toLowerCase())
case yes
 await clickElement('click', 'selector', this.d255YesInput);
case no
 await clickElement('click', 'selector', this.d255NoInput);

Why is the condition for d255 to no be 'na'

2022-03-29 20:18 UTC, dhDVSA approved these changes

2022-03-30 07:55 UTC, Cullima approved these changes

2022-03-30 07:55 UTC, Cullima commented on src/pageobjects/des/finalOutcomeScreen.pageobject.ts
> +      if (provisionalLicenceReceived.toLowerCase() === 'yes') {
why do we need the outer `if`?

2022-03-30 07:55 UTC, Cullima commented on src/pageobjects/des/finalOutcomeScreen.pageobject.ts
> +    if (d255.toLowerCase() !== 'na') {
same comment here

2022-03-30 07:55 UTC, Cullima commented on src/pageobjects/des/office.pageobject.ts
> +    if (activityCode.toLowerCase() !== 'na') {
mark as `@TODO` if further work required

2022-03-30 07:55 UTC, Cullima commented on src/pageobjects/des/office.pageobject.ts
> +    if (independentDriving.toLowerCase() !== 'na') {
same comment with these outer `if`s

2022-03-30 09:19 UTC, matthew2564 commented on src/pageobjects/des/finalOutcomeScreen.pageobject.ts
> +    }
If you wanted to remove the 3 if statements into one, you could do something like this

```
    const transmissionValue = transmission?.toLowerCase();

    if (transmissionValue !== 'na') {
      await clickElement(
        'click',
        'selector',
        transmissionValue === 'manual' ? this.transmissionManualInput : this.transmissionAutomaticInput,
      );
    }
```

2022-04-05 08:03 UTC, Cullima requested changes

2022-04-05 08:20 UTC, Cullima approved these changes

2022-04-05 08:21 UTC, merged