Mes 7805 cat b unsuccessful serious serious
dvsa/dvsa-des-automation pull request #75
Opened 2022-04-26 12:26 UTC by solomonsimukoko

Mes 7805 cat b unsuccessful serious serious

## Checklist

- [ ] PR title includes the JIRA ticket number and an understandable description
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket

2022-04-26 12:51 UTC, matthew2564 commented on src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWithSeriousFaults.feature
> +    And I wait on element "//ion-header//ion-buttons/ion-back-button" to be displayed
Should this be using the global elements alias pattern?

2022-04-26 12:53 UTC, matthew2564 commented on src/pageobjects/des/nonPassFinalisation.pageobject.ts
> +  }
Are these used? If so, they should be async/await.

2022-04-26 12:57 UTC, turnerc1 requested changes

2022-04-26 12:57 UTC, turnerc1 commented on src/element-references/des-element-references.json
> +      "status-fail" : "#status-fail",
This already exists as "test-outcome-failed", 3 lines below

2022-04-26 12:57 UTC, turnerc1 commented on src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWithSeriousFaults.feature
> +  Scenario:   Successful test with 15 faults
This is not a tests with 15 faults, it is a tests with serious faults. Change the name please.

2022-04-26 12:57 UTC, turnerc1 commented on src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWithSeriousFaults.feature
> +    And I wait on element "des-final-confirmation-screen::page-title" to be displayed
Add the the step to check for the confirmation screen, check the other feature files for it. It should be, something like "And I check the confirmation page details from a data table"

2022-04-26 12:57 UTC, turnerc1 commented on src/features/des/cat-b/UnsuccessfulTests/UnsuccessfulTestWithSeriousFaults.feature
> +    And I pause for 2000ms
Is this pause needed?

2022-04-26 14:12 UTC, turnerc1 requested changes

2022-04-26 14:12 UTC, turnerc1 commented on src/pageobjects/des/nonPassFinalisation.pageobject.ts
> +import checkEqualsText from '@shared-boilerplate/support/check/checkEqualsText';
I think that these can just go in the finalise outcome page. The non-pass and pass finalisation page are the same.

2022-04-28 12:51 UTC, gabrielngdvsa approved these changes

2022-04-28 12:58 UTC, turnerc1 requested changes

2022-04-28 12:58 UTC, turnerc1 commented on src/element-references/des-element-references.json
> +    "continue-to-non-pass-finalisation": "#continue-to-non-pass-finalisation"
is this in the correct place?

2022-04-28 12:58 UTC, turnerc1 commented on src/element-references/des-element-references.json
> +      "serious-comment": "#fault-comment-text-serious-controlsAccelerator"
change to represent what fault it is for please. e.g. "serious-comment-controls-accelerator"

2022-04-28 12:58 UTC, turnerc1 commented on src/element-references/des-element-references.json
> +      "fault-comment-eyesight-input": "#fault-comment-text-serious-eyesightTest",
change to represent what fault type it is for please. e.g. "serious-fault-comment-eyesight-input"

2022-04-28 12:58 UTC, turnerc1 commented on src/element-references/des-element-references.json
>        "fault-comment-input": "#fault-comment-text-driving-controlsAccelerator",
change to represent what fault it is for please. e.g. "driving-fault-controls-acelerator-comment-input"

2022-04-28 13:07 UTC, Cullima commented on src/element-references/des-element-references.json
> +    "continue-to-non-pass-finalisation": "#continue-to-non-pass-finalisation"
agree should belong to the page

2022-04-29 08:16 UTC, matthew2564 approved these changes

2022-04-29 08:48 UTC, merged