MES-7485 - Rekey Terminate
dvsa/dvsa-des-automation pull request #85
Opened 2022-05-17 09:26 UTC by gabrielngdvsa

## Description

* PLEASE INSERT DESCRIPTION

## Checklist

- [ ] PR title includes the JIRA ticket number and an understandable description
- [ ] Branch is rebased against the latest develop
- [ ] Code has been tested manually
- [ ] PR link added to JIRA ticket

2022-05-17 13:58 UTC, matthew2564 commented on src/pageobjects/des/rekeyReason.pageobject.ts
> +      console.log('WOW: ', field, fieldInput);
Please remove

2022-05-17 13:58 UTC, matthew2564 commented on src/pageobjects/des/rekeyReason.pageobject.ts
> +            console.log('Tick Ipad');
Are all of these logs necessary?

2022-05-17 13:58 UTC, turnerc1 requested changes

2022-05-18 10:47 UTC, gabrielngdvsa commented on src/pageobjects/des/rekeyReason.pageobject.ts
> +      console.log('WOW: ', field, fieldInput);
removed

2022-05-18 10:47 UTC, gabrielngdvsa commented on src/pageobjects/des/rekeyReason.pageobject.ts
> +            console.log('Tick Ipad');
removed

2022-05-18 10:47 UTC, gabrielngdvsa commented on src/features/des/cat-b/TerminatedTests/TerminatedTestsRekey.feature
> +      | activityCode                  | des-final-outcome-screen::activity-code-21   |
have modified inputs

2022-05-18 10:48 UTC, gabrielngdvsa commented on src/features/des/cat-b/TerminatedTests/TerminatedTestsRekey.feature
> +    And I complete the Office unsuccessful page from a data table
modified

2022-05-18 10:48 UTC, gabrielngdvsa commented on config/suites/des.suites.ts
> +    '.src/features/des/cat-b/TerminatedTests/TerminatedTestsRekey.feature',
confirmed yes since its cat b and belong to terminated tests

2022-05-18 10:48 UTC, gabrielngdvsa commented on src/pageobjects/des/rekeyReason.pageobject.ts
> +    data: Record<keyof OfficePageData, string>,
updated

2022-05-18 10:48 UTC, gabrielngdvsa commented on src/features/des/cat-b/TerminatedTests/TerminatedTestsRekey.feature
> +    And I check the confirmation page details from a data table
updated

2022-05-18 11:56 UTC, turnerc1 requested changes

2022-05-18 11:56 UTC, turnerc1 commented on config/suites/des.suites.ts
> +    '.src/features/des/cat-b/TerminatedTests/TerminatedTestsRekey.feature',
Add your test to the TerminateTests suite as well

2022-05-18 11:57 UTC, turnerc1 approved these changes

2022-05-18 13:46 UTC, matthew2564 approved these changes

2022-05-18 13:48 UTC, merged